# Generated by Django 4.0.3 on 2022-04-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_publicmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicmail',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
