# Generated by Django 4.0.3 on 2022-04-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_category_share_like_forum_comment_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='post_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='share',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forum',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forum',
            name='share',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Share',
        ),
    ]
