# Generated by Django 4.0.3 on 2022-04-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_remove_share_user_comment_post_id_comment_post_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
