# Generated by Django 4.0.3 on 2022-04-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comment',
            field=models.ManyToManyField(to='dash.comment'),
        ),
    ]
