# Generated by Django 4.0.3 on 2022-04-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0016_alter_blog_pub_date_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='value',
        ),
        migrations.AddField(
            model_name='like',
            name='is_liked',
            field=models.BooleanField(null=True),
        ),
    ]
