# Generated by Django 4.0.3 on 2022-04-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0018_remove_blog_like_remove_forum_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='is_like',
            field=models.BooleanField(null=True),
        ),
    ]
