# Generated by Django 4.0.3 on 2022-04-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0019_like_is_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(null=True)),
                ('post_type', models.CharField(max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ipaddress', models.GenericIPAddressField(null=True)),
                ('user_a', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
