# Generated by Django 4.0.3 on 2022-04-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0020_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='share',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='share',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='view',
        ),
        migrations.AddField(
            model_name='blog',
            name='view',
            field=models.ManyToManyField(to='dash.view'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='pub_date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
