# Generated by Django 4.0.3 on 2022-04-23 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0021_remove_blog_share_remove_forum_share_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='view',
        ),
    ]
