# Generated by Django 4.0.3 on 2022-04-23 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0023_completeblog_alter_forum_category_alter_forum_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompleteBlog',
        ),
    ]
