# Generated by Django 4.0.3 on 2022-04-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0024_delete_completeblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
