# Generated by Django 4.0.3 on 2022-04-23 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0025_alter_forum_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forums', to='dash.category'),
        ),
    ]
