# Generated by Django 4.0.3 on 2022-04-23 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0026_alter_forum_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='content',
            new_name='title',
        ),
    ]
